config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "posts#index"
  get 'pages/iletisim'
  devise_for :users
  resources :posts do
    member do
      put "like", to: "posts#like"
      put "unlike", to: "posts#unlike"
    end
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthabley
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, styles: { thumb: "80x80>",mini: "25x25>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if:  :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post

  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user= current_user

    respond_to do |format|
      if @comment.save
        format.js
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post=Post.find(params[:post_id])
      #@comment = @post.comments.find(params[:id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:bdy)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def iletisim
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :kontrol,:destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :kontrol, only: [:edit,:destroy]
  # GET /posts
  # GET /posts.json
  def index

    if params[:user]
      @posts = Post.where(user: params[:user]).order("created_at DESC")
    else
       @posts = Post.all.order("created_at DESC")
    end
    @post=Post.new
  end

def kontrol

redirect_to posts_path, notice: "Yetkiniz Bulunmamaktadir" unless current_user==@post.user



end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @likeds=Like.where(post: @post).all
    @comments=@post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user=current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @l=Like.new
    @l.post=@post
    @l.user=current_user
    @l.save
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  def unlike
    @l=Like.where(post:@post,user:current_user).first
    @l.destroy
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :msg, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<div class="row">
<div class="col-md-6">
<%= form_for([@post, Comment.new], :remote=>'true', :controller => 'comments', :action => 'create') do |f| %>
<div class="row">
 <div class="col-md-9">
  <div class="form-group">
    <%= f.text_field :bdy, id: :comment_bdy, class:"form-control" %>
  </div>
  </div>
  <div class="col-md-3">
  <div class="actions">
    <%= f.submit "Yorum At", class:"form-action btn btn-info"  %>
  </div>
</div>
</div>
<% end %>
</div>
</div>

app/views/comments/create.js.erb
$('#comments').append('<%=image_tag @comment.user.image.url(:mini) if @comment.user.image? %> <em><%=@comment.user.name%> </em> <b> <%=@comment.bdy%> </b><br/>');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Bdy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.bdy %></td>
        <td><%= link_to 'Show', comment %></td>

        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bdy:</strong>
  <%= @comment.bdy %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<title>hatoztml</title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>

  <body>
    <style type="text/css">
      #ana_div {

    height: 100px;
    width: 960px;
    margin-right: auto;
    margin-left: auto;


}
.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}

.div {
    float: left;
    display: inline-block;
    height: 200px;
    width: 220px;
    margin: 10px;
    border: 1px solid #000000;

}
.footer1 {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1rem;
  background-color: #efefef;
  text-align: center;
}
.footer-bottom {
    background-color: gray;
    border:10px solid;
    min-height: 30px;
    width: 100%;
}
.copyright {
    color: #fff;
    line-height: 30px;
    min-height: 30px;
    padding: 7px 0;
}
  </style>
    <nav class="ntopnav">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%=link_to "Ana Sayfa", posts_path, class:"navbar-brand"%>
  <%=link_to "Hakkimizda", posts_path, class:"navbar-brand"%>
  <%=link_to "Iletisim", pages_iletisim_path, class:"navbar-brand"%>

</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li> <%= link_to '', new_post_path, class:"glyphicon glyphicon-plus" %> </li>
    <li class="dropdown">
        <% if user_signed_in? %>
        <br>
              <em><%=image_tag current_user.image.url(:mini) if current_user.image?%> </em>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.name%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Çıkış", destroy_user_session_path, :method => :delete %></li>
              <li><%= link_to "Ayarlar", edit_user_registration_path%></li>
            </ul>
          </li>
        <% else %>
           <li><%= link_to('Giriş Yap', new_user_session_path) %></li>
           <li><%= link_to('Üye Ol', new_user_registration_path) %></li>
        <% end %>

      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<div class="container-fluid main-container">
<div class="col-md-12 content">
  <%= yield %>
</div>
<footer class="container-fluid main-container" style="background-color: #efefef;
text-align: center;">
  <p class="col-md-12">
    <hr class="divider">
    Twitter : hatoztml </a>
  </p>
</footer>
</div>
  </body>
</html>

app/views/pages/iletisim.html.erb
<!DOCTYPE html>

<html>

<head>

<style>

input[type=text], select, textarea {

    width: 100%;

    padding: 12px;

    border: 1px solid #ccc;

    border-radius: 4px;

    box-sizing: border-box;

    margin-top: 6px;

    margin-bottom: 16px;

    resize: vertical;

}

​

input[type=submit] {

    background-color: #4CAF50;

    color: white;

    padding: 12px 20px;

    border: none;

    border-radius: 4px;

    cursor: pointer;

}

​

input[type=submit]:hover {

    background-color: #45a049;

}

​

.container {

    border-radius: 5px;

    background-color: #f2f2f2;

    padding: 20px;

}

</style>

</head>

<body>

​

<h3>Contact Form</h3>

​

<div class="container">

  <form action="/pages/iletisim">

    <label for="fname">Isim</label>
<br>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

​
<br>
<br>
    <label for="lname">Soyad</label>
<br>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">
<br>
<br>
    <label for="lname">Telefon</label>
<br>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">
<br>
<br>
    <label for="country">Country</label>
<br>
    <select id="country" name="country">

      <option value="australia">Australia</option>

      <option value="canada">Canada</option>

      <option value="usa">USA</option>

      <option value="usa">Turkey</option>

    </select>
<br>
<br>​

    <label for="subject">Mesajiniz</label>
<br>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>
<br><br>
​

    <input type="submit" value="Gonder">

  </form>

</div>

​

</body>

</html>

​

app/views/posts/_form.html.erb
<%= form_for(post, remote: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :msg %>
    <%= form.text_area :msg, id: :post_msg,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :post_image,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Oluştur", class:"form-control btn btn-success" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
    <div class="container">
 
<br></br>
<br></br>
        <div class="row">
          <% @posts.each do |post| %>

            <div class="panel panel-default widget">

                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-2 col-md-1">
                                    <%=image_tag post.user.image.url(:thumb) if post.user.image?%>
                                </div>
                                <div class="col-xs-10 col-md-11">
                                    <div>
                                        <div class="mic-info">
                                             <a href="?user=<%=post.user.id%>"> <%=post.user.name%> </a> <%=post.created_at%>
                                        </div>
                                    </div>



                                    <div class="comment-text">
                                        <%=post.title%> <br/>
                                        <%=image_tag post.image.url(:medium),class:"img img-responsive" if post.image?%>
                                        <br/>
                                        <%=post.msg%>
                                    </div>
                                    <hr>
                                    <div class="action">
                                     <% if post.user == current_user  %>
                                      <%= link_to '', post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %>

                                      <%= link_to '', edit_post_path(post),class:"glyphicon glyphicon-pencil" %>
<%end%>
                                      <%= link_to '', post_path(post),class:"glyphicon glyphicon-hand-right" %>
                                      <hr>

                                   <% if user_signed_in? %>
                                      <div id="<%=post.id%>">
                                      <%if Like.where(user:current_user, post:post).count>0%>
                                         <%= link_to "", unlike_post_path(post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                                      <%else%>
                                         <%= link_to "", like_post_path(post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                                      <%end%>
                                      <%end%>
                                      </div>
                                      <hr>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <%end%>
        </div>
    </div>

app/views/posts/like.js.erb
$('#<%=@post.id%>').html('<%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>')

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class="panel panel-default widget">
  <div class="panel-body">
    <%= render 'form', post: @post %>
  </div>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="panel panel-default widget">

    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row">
                    <div class="col-xs-2 col-md-1">
                        <%=image_tag @post.user.image.url(:mini) if @post.user.image?%>
                    </div>
                    <div class="col-xs-10 col-md-11">
                        <div>
                            <div class="mic-info">
                                 <a href="?user=<%=@post.user.id%>"> <%=@post.user.name%> </a> <%=@post.created_at%>
                            </div>
                        </div>
                        <div class="comment-text">
                            <%=@post.title%> <br/>
                            <%=image_tag @post.image.url(:medium),class:"img img-responsive" if @post.image?%>
                            <br/>
                            <%=@post.msg%>
                        </div>
                        <hr>
                        <div class="action">
                          <%= link_to '', @post, :method => :delete, data: {confirm: 'Eminmisin?',commit: 'Evet'},class:"glyphicon glyphicon-trash" %>
                          <%= link_to '', edit_post_path(@post),class:"glyphicon glyphicon-pencil" %>

                          <div id="<%=@post.id%>">
                          <%if Like.where(user:current_user, post:@post).count>0%>
                             <%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                          <%else%>
                             <%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                          <%end%>
                          </div>
                        </div>
                        <hr>
                        <%=render 'comments/form'%>
                        Bunu beğenler(<%=@likeds.count%>) <br/>
                        <% @likeds.each do |l|%>
                          <%=l.user.name%>
                        <% end %>
                        <hr>
                        <div id="comments">
                        <%@comments.each do |c|%>
                         <%=image_tag c.user.image.url(:mini) if c.user.image?%> <em> <%=c.user.name%> </em> <b><%=c.bdy%> </b>    <br/>
                        <%end%>
                      </div>

                    </div>
            </li>
        </ul>
    </div>
</div>

app/views/posts/unlike.js.erb
$('#<%=@post.id%>').html('<%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>')